import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Oswald } from 'next/font/google';
import CursorBubble from '@/app/components/common/CursorBubble'
import MenuBar from '@/app/components/common/MenuBar'

const oswald = Oswald({ subsets: ['latin'], weight: ['200'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${oswald.className}`}
      >
        <CursorBubble />
        <MenuBar />
        {children}
      </body>
    </html>
  );
}
